---
title: '--- Day 3: Toboggan Trajectory ---'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The Challenge

This can be read [here](https://adventofcode.com/2020/day/3)

## The Solution

### Reading in Data

```{r}
trees <- readLines(
  here::here("puzzles", "day_03", "input.txt")
)

head(trees)
```

### Part 1

```{r}

mod <- function(n, div) {
  n - ((n - 1) %/% div)*div
}

how_many_trees <- function(trees, right = 3, down = 1) {
  trees_mat <- matrix(
    unlist(strsplit(trees, "")), 
    nrow = length(trees), byrow = TRUE
  )
  rows <- seq(from = 1 + down, to = nrow(trees_mat), by = down)
  cols <- mod(seq(from = 1 + right, by = right, length.out = length(rows)), ncol(trees_mat))
  
  sum(
    sapply(seq_along(rows), function(i) {
      trees_mat[rows[i], cols[i]] == "#"
    })
  )
}

how_many_trees(trees)
```

### Part 2

```{r}
Reduce(
  `*`,
  c(
    how_many_trees(trees, right = 1, down = 1),
    how_many_trees(trees, right = 3, down = 1),
    how_many_trees(trees, right = 5, down = 1),
    how_many_trees(trees, right = 7, down = 1),
    how_many_trees(trees, right = 1, down = 2)
  )
)
```

